### ISSUE TITLE
Consider enabling Github pages 

### ISSUE THREAD

**Issue by alphaolomi** [thank-you-php/thank-you-php#370]
### Consider enabling Github pages 

Github pages, even with the default settings is enough to turn this repo into a website

This will extend the reach, visibility, SEO etc

**Comment by Ahmard** [comment]
Yes, GH pages please.

**Comment by yinlinghunjiang** [comment]
@petk A Gh pages for all the contributors plz !

**Comment by petk** [comment]
Sure, let's do this as well. :) Coming up... https://github.com/thank-you-php/thank-you-php.github.io

**Comment by petk** [comment]
Marking this as resolved. Github pages enabled: https://thank-you-php.github.io

It will be improved later on also. Cheers.
